#!/bin/bash

LAST="$1"
shift
if [ -z "${LAST}" ]; then
	if [ -e "./last.panel" ]; then
		LAST="$(cat last.panel)"
	else
		LAST="https://www.schisslaweng.net/mach-doch-mal/"
	fi
fi
echo Found $LAST

LAST_HTML="$(curl --silent ${LAST})"

NEXT="$(echo $LAST_HTML|grep -o 'value="http.*/"> '| grep -o 'https:[^ "]\+' |sort -R|head -1|tee last.panel)"
echo Next $NEXT


PANELS="$(curl --silent "$NEXT" | grep -o 'https[^ ]\+ 1280w' | cut -d' ' -f1|tr '\n' ' ')"

echo Panels $PANELS 

DOIT="montage -background none -tile 1x -geometry +20+10 $PANELS panels.png"
echo $DOIT
$DOIT

if command -v termux-open > /dev/null; then
	termux-open panels.png
fi
